# Generated by Django 4.0 on 2022-02-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response_pdf',
            name='image_content',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='response_pdf',
            name='text_content',
            field=models.CharField(max_length=1000),
        ),
    ]
